### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by jaapjansma** [giant-rabbit/com.giantrabbit.civimailchimp#2]
When trying to connect to mailchimp curl issues the following error: unable to get local issuer certificate.

Following this answer on stackexchange I have fixed the error: http://stackoverflow.com/a/28886953/3853493

**Comment by anemirovsky** [comment]
The problem with this fix is that it disables verification of the SSL certificate by the server making a request to the Mailchimp API servers. In general, these should always remain enabled when making these API requests.

Disabling these options does stop the error you noted, but it doesn't fix the underlying problem, which is that there is some SSL configuration problem on your server that's making the request to Mailchimp that you'll want to fix. Based on some Google searches it may be a problem with the Certificate Authorities list on your machine being missing or out of date: http://stackoverflow.com/a/19149687/4230923. I would recommend fixing the underlying issue.

**Comment by jaapjansma** [comment]
@anemirovsky you are right about the certificates and server setup. However the problem I have is that it is a hosted civicrm and I am not the server manager. So I have to check whether the hoster can solve this. I hope they can do.
